### Arange

**`arange([start] [stop] [step], [dtype=None])`**

In [1]:
import numpy as np

In [3]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
x = range(1, 10)
print(x) # x is iterator, not an array
print(list(x)) # convert to list to see the values

In [6]:
x = np.arange(0.9, 10.5, 2.3, int)
print(x)

[ 0  3  6  9 12]


### Linspace

**`linspace(start, stop num=50, endpoint=True, retstep=False)`**

In [10]:
print(np.linspace(1, 10, 5)) # 5 value from 1 to 10, equally spaced
print(np.linspace(1, 10, 5, endpoint=False)) # exclude the endpoint (10)
print(np.linspace(1, 10, 5, retstep=True)) # return the step size as well

[ 1.    3.25  5.5   7.75 10.  ]
[1.  2.8 4.6 6.4 8.2]
(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), np.float64(2.25))


### Zero-Dimensional array in Numpy

In [12]:
x = np.array([5])
print(x)
print(x.shape) # shape of the array
print(x.ndim) # number of dimensions

[5]
(1,)
1


### One-Deminsional Array

In [13]:
X = np.array((1, 2, 3, 4, 6, 8))
print(X)
print(X.shape)
print(X.ndim)

[1 2 3 4 6 8]
(6,)
1


### Two-Demensial Array

In [18]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(X.shape)
print(X.ndim)

Y = np.array([ 
    [[111, 112, 112], [121, 122, 112]],
    [[211, 212, 112], [221, 222, 112]],
    [[311, 312, 112], [321, 322, 112]] 
])

print("\n\n")
print(Y)
print(Y.shape)
print(Y.ndim)

(3, 3)
2



[[[111 112 112]
  [121 122 112]]

 [[211 212 112]
  [221 222 112]]

 [[311 312 112]
  [321 322 112]]]
(3, 2, 3)
3


In [23]:
S = np.array([i for i in range(1, 10)])

print(S[2:5])
print(S[:4])
print(S[6:])


[3 4 5]
[1 2 3 4]
[7 8 9]


In [24]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A[:3, 2:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [27]:
E = np.ones((2, 3))
print(E)

[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
Z = np.zeros((2, 4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
x = np.array([[1, 2, 3], [4, 5, 6]], order="F")
y = x.copy()

x[0][0] = 1001

print(x, end="\n\n")
print(y)


[[1001    2    3]
 [   4    5    6]]

[[1 2 3]
 [4 5 6]]


In [34]:
np.identity(4) # main diagonal is 1 others 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.eye(5, 8, k=1, dtype=int) # like an identity but diagonal moved k

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

## Exercises

### Ex 1

In [44]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8])

### Ex 2

In [54]:
odd_elements = v[0::2]
print(odd_elements)
rever_order = v[::-1]
print(rever_order)

[1 3 5 7]
[8 7 6 5 4 3 2 1]
