### Arange

**`arange([start] [stop] [step], [dtype=None])`**

In [2]:
import numpy as np

In [3]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [4]:
x = range(1, 10)
print(x) # x is iterator, not an array
print(list(x)) # convert to list to see the values

range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
x = np.arange(0.9, 10.5, 2.3, int)
print(x)

[ 0  3  6  9 12]


### Linspace

**`linspace(start, stop num=50, endpoint=True, retstep=False)`**

In [6]:
print(np.linspace(1, 10, 5)) # 5 value from 1 to 10, equally spaced
print(np.linspace(1, 10, 5, endpoint=False)) # exclude the endpoint (10)
print(np.linspace(1, 10, 5, retstep=True)) # return the step size as well

[ 1.    3.25  5.5   7.75 10.  ]
[1.  2.8 4.6 6.4 8.2]
(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), np.float64(2.25))


### Zero-Dimensional array in Numpy

In [7]:
x = np.array([5])
print(x)
print(x.shape) # shape of the array
print(x.ndim) # number of dimensions

[5]
(1,)
1


### One-Deminsional Array

In [8]:
X = np.array((1, 2, 3, 4, 6, 8))
print(X)
print(X.shape)
print(X.ndim)

[1 2 3 4 6 8]
(6,)
1


### Two-Demensial Array

In [9]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(X.shape)
print(X.ndim)

Y = np.array([ 
    [[111, 112, 112], [121, 122, 112]],
    [[211, 212, 112], [221, 222, 112]],
    [[311, 312, 112], [321, 322, 112]] 
])

print("\n\n")
print(Y)
print(Y.shape)
print(Y.ndim)

(3, 3)
2



[[[111 112 112]
  [121 122 112]]

 [[211 212 112]
  [221 222 112]]

 [[311 312 112]
  [321 322 112]]]
(3, 2, 3)
3


In [10]:
S = np.array([i for i in range(1, 10)])

print(S[2:5])
print(S[:4])
print(S[6:])


[3 4 5]
[1 2 3 4]
[7 8 9]


In [11]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A[:3, 2:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [12]:
E = np.ones((2, 3))
print(E)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
Z = np.zeros((2, 4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
x = np.array([[1, 2, 3], [4, 5, 6]], order="F")
y = x.copy()

x[0][0] = 1001

print(x, end="\n\n")
print(y)


[[1001    2    3]
 [   4    5    6]]

[[1 2 3]
 [4 5 6]]


In [15]:
np.identity(4) # main diagonal is 1 others 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(5, 8, k=1, dtype=int) # like an identity but diagonal moved k

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

## Exercises

### Ex 1

In [17]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8])

### Ex 2

In [18]:
odd_elements = v[0::2]
print(odd_elements)
rever_order = v[::-1]
print(rever_order)

[1 3 5 7]
[8 7 6 5 4 3 2 1]


## Data Types


In [22]:
i16 = np.dtype(np.int16)

print(i16)


lst = [
    [3.4, 8.7, 9.9],
    [1.1, -7.8, -0.7],
    [4.1, 12.3, 4.8]
]

A = np.array(lst, dtype=i16)
print(A)

int16
[[ 3  8  9]
 [ 1 -7  0]
 [ 4 12  4]]


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [27]:
dt = np.dtype([('density', np.int32)])

x = np.array([(345,), (456,), (654,) ], dtype=dt)

print(x)

print(repr(x))

[(345,) (456,) (654,)]
array([(345,), (456,), (654,)], dtype=[('density', '<i4')])


**We can access the content of density column bu indexing x with the key**

In [28]:
print(x['density'])

[345 456 654]


In [47]:
dt = np.dtype([
    ('country', np.str_, 20), # ('country', "U20"), 
    ('density', np.int32),
    ('area', np.int32),
    ('population', np.int32)
])

population_table = np.array([
    ('Netherlands', 393, 41526, 16928800),
    ('Belgium', 337, 30510, 11007020),
    ('United Kingdom', 256, 243610, 62262000),
    ('Germany', 233, 357021, 81799600),
    ('Liechtenstein', 205, 160, 32842),
    ('Italy', 192, 301230, 59715625),
    ('Switzerland', 177, 41290, 7301994),
    ('Luxembourg', 173, 2586, 512000),
    ('France', 111, 547030, 63601002),
    ('Austria', 97, 83858, 8169929),
    ('Greece', 81, 131940, 11606813),
    ('Ireland', 65, 70280, 4581269),
    ('Sweden', 20, 449964, 9515744),
    ('Finland', 16, 338424, 5410233),
    ('Norway', 13, 385252, 5033675)
], dtype=dt)

print(population_table['country'][2:5])
print(population_table['density'])

['United Kingdom' 'Germany' 'Liechtenstein']
[393 337 256 233 205 192 177 173 111  97  81  65  20  16  13]


In [49]:
# To save csv file

np.savetxt(
    "population_table.csv",
    population_table,
    fmt="%s;%d;%d;%d",
    delimiter=";"
)

In [54]:
x = np.genfromtxt(
    "population_table.csv",
    dtype=dt,
    delimiter=";"
)
print(type(x))

# print(x)

print(x['country'])
print(x['population'])

<class 'numpy.ndarray'>
['Netherlands' 'Belgium' 'United Kingdom' 'Germany' 'Liechtenstein'
 'Italy' 'Switzerland' 'Luxembourg' 'France' 'Austria' 'Greece' 'Ireland'
 'Sweden' 'Finland' 'Norway']
[16928800 11007020 62262000 81799600    32842 59715625  7301994   512000
 63601002  8169929 11606813  4581269  9515744  5410233  5033675]


In [55]:
dt_products = np.dtype([
    ('id', np.int32),
    ('price', np.int32),
    ('name', np.str_, 100)
])

product_data = [
    (1, 25, "Wireless Mouse"),
    (2, 89, "Mechanical Keyboard"),
    (3, 45, "USB-C Hub"),
    (4, 299, "Ergonomic Chair")
]

products = np.array(product_data, dtype=dt_products)

new_item = np.array([(5, 120, "Portable SSD")], dtype=dt_products)
products = np.append(products, new_item)

print(products)
print(f"Product Names: {products['name']}")



[(1,  25, 'Wireless Mouse') (2,  89, 'Mechanical Keyboard')
 (3,  45, 'USB-C Hub') (4, 299, 'Ergonomic Chair')
 (5, 120, 'Portable SSD')]
Product Names: ['Wireless Mouse' 'Mechanical Keyboard' 'USB-C Hub' 'Ergonomic Chair'
 'Portable SSD']


## Operations on array

In [ ]:
lst = [i for i in range(2, 40, 4)]

v = np.array(lst)

print(v)
v = v + 2
print(v)

[ 2  6 10 14 18 22 26 30 34 38]
[ 4  8 12 16 20 24 28 32 36 40]


In [60]:
cities = [
    "Barcelona", "Berlin", "Brussels", "Bucharest",
    "Budapest", "Copenhagen", "Dublin", "Hamburg", "Istanbul",
    "Kiev", "London", "Madrid", "Milan", "Moscow", "Munich",
    "Paris", "Prague", "Rome", "Saint Petersburg",
    "Stockholm", "Vienna", "Warsaw"
]

dist2barcelona = [
    0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391, 1138, 505, 725, 3007, 1055, 833, 1354, 857, 2813, 2277, 1347, 1862
]

dists = np.array(dist2barcelona[:12])

print(dists)

print(np.abs(dists - dists[:, np.newaxis]))

[   0 1498 1063 1968 1498 1758 1469 1472 2230 2391 1138  505]
[[   0 1498 1063 1968 1498 1758 1469 1472 2230 2391 1138  505]
 [1498    0  435  470    0  260   29   26  732  893  360  993]
 [1063  435    0  905  435  695  406  409 1167 1328   75  558]
 [1968  470  905    0  470  210  499  496  262  423  830 1463]
 [1498    0  435  470    0  260   29   26  732  893  360  993]
 [1758  260  695  210  260    0  289  286  472  633  620 1253]
 [1469   29  406  499   29  289    0    3  761  922  331  964]
 [1472   26  409  496   26  286    3    0  758  919  334  967]
 [2230  732 1167  262  732  472  761  758    0  161 1092 1725]
 [2391  893 1328  423  893  633  922  919  161    0 1253 1886]
 [1138  360   75  830  360  620  331  334 1092 1253    0  633]
 [ 505  993  558 1463  993 1253  964  967 1725 1886  633    0]]
